[build]
  base = ".."
  command = "cd packages/curriculum-schemas && npm install && npm run build && cd ../../kalam-curriculum-dashboard && npm install && npm run build"
  publish = "kalam-curriculum-dashboard/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for Next.js pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
