'use client';

import { useState } from 'react';
import { Modal } from '../ui/Modal';
import type { Topic, CreateTopic, UpdateTopic } from '@/lib/schemas/curriculum';
import { useCreateTopic, useUpdateTopic } from '@/lib/hooks/useTopics';
import { useLetters, type Letter } from '@/lib/hooks/useLetters';
import { ArabicLetterGrid, type LetterForm } from './forms/ArabicLetterGrid';

interface TopicFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  curriculumId: string;
  topic?: Topic | null;
}

export function TopicFormModal({
  isOpen,
  onClose,
  curriculumId,
  topic,
}: TopicFormModalProps) {
  const isEdit = Boolean(topic);
  const { mutate: createTopic, isPending: isCreating } = useCreateTopic();
  const { mutate: updateTopic, isPending: isUpdating } = useUpdateTopic();
  const { letters, loading: lettersLoading } = useLetters();

  const [useCustomInput, setUseCustomInput] = useState(false);
  const [customTopicName, setCustomTopicName] = useState('');
  const [topicType, setTopicType] = useState<'lesson' | 'review' | 'quiz' | 'assessment'>('lesson');

  const [selectedLetter, setSelectedLetter] = useState<Letter | null>(
    topic?.metadata?.reference?.id
      ? letters.find(l => l.id === topic.metadata?.reference?.id) || null
      : null
  );

  const [selectedForm, setSelectedForm] = useState<LetterForm>(
    (topic?.metadata?.reference?.form as LetterForm) || 'isolated'
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    let data: CreateTopic | UpdateTopic;

    if (useCustomInput) {
      if (!customTopicName.trim()) {
        return; // Should not happen due to form validation
      }

      data = {
        title: {
          en: customTopicName.trim(),
          ar: customTopicName.trim(),
        },
        description: {
          en: customTopicName.trim(),
          ar: customTopicName.trim(),
        },
        type: topicType,
        // No letter_id for custom topics
      };
    } else {
      if (!selectedLetter) {
        return; // Should not happen due to form validation
      }

      // Auto-generate title and description from letter data
      const formNames = {
        isolated: { en: 'Isolated', ar: 'منفصل' },
        initial: { en: 'Initial', ar: 'أول' },
        medial: { en: 'Medial', ar: 'وسط' },
        final: { en: 'Final', ar: 'آخر' },
      };

      const titleEn = `Letter ${selectedLetter.name_english} (${formNames[selectedForm].en} Form)`;
      const titleAr = `حرف ${selectedLetter.name_arabic} (شكل ${formNames[selectedForm].ar})`;
      const formCharacter = selectedLetter.forms[selectedForm];
      const descriptionEn = `Learn the ${formNames[selectedForm].en.toLowerCase()} form of the Arabic letter ${selectedLetter.name_english}: ${formCharacter}`;
      const descriptionAr = `تعلم الشكل ${formNames[selectedForm].ar} من حرف ${selectedLetter.name_arabic}: ${formCharacter}`;

      data = {
        title: {
          en: titleEn,
          ar: titleAr,
        },
        description: {
          en: descriptionEn,
          ar: descriptionAr,
        },
        letter_id: selectedLetter.id, // Just send the letter ID, backend will fetch full data
        letter_form: selectedForm, // Send the selected form (isolated, initial, medial, final)
        type: topicType,
        // sequence_number will be auto-generated by backend if not provided
      };
    }

    if (isEdit && topic) {
      updateTopic(
        {
          curriculumId,
          topicId: topic.id,
          data: data as UpdateTopic,
        },
        {
          onSuccess: () => {
            onClose();
          },
        }
      );
    } else {
      createTopic(
        {
          curriculumId,
          data: data as CreateTopic,
        },
        {
          onSuccess: () => {
            onClose();
          },
        }
      );
    }
  };

  const handleClose = () => {
    setSelectedLetter(null);
    setSelectedForm('isolated');
    setUseCustomInput(false);
    setCustomTopicName('');
    setTopicType('lesson');
    onClose();
  };

  const handleLetterSelect = (letter: Letter) => {
    setSelectedLetter(letter);
    setSelectedForm('isolated'); // Default to isolated form when changing letter
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={handleClose}
      title={isEdit ? 'Edit Topic' : useCustomInput ? 'Create New Topic' : 'Select Letter for New Topic'}
    >
      <form onSubmit={handleSubmit} className="p-6">
        {/* Toggle for custom input */}
        {!isEdit && (
          <div className="mb-6 flex items-center justify-between">
            <span className="text-sm font-medium text-gray-700">
              {useCustomInput ? 'Custom Topic Name' : 'Select from Letters'}
            </span>
            <button
              type="button"
              onClick={() => {
                setUseCustomInput(!useCustomInput);
                setSelectedLetter(null);
                setCustomTopicName('');
              }}
              className={`
                relative inline-flex h-6 w-11 items-center rounded-full transition-colors
                ${useCustomInput ? 'bg-blue-600' : 'bg-gray-300'}
              `}
            >
              <span
                className={`
                  inline-block h-4 w-4 transform rounded-full bg-white transition-transform
                  ${useCustomInput ? 'translate-x-6' : 'translate-x-1'}
                `}
              />
            </button>
          </div>
        )}

        {/* Topic Type Selector */}
        {!isEdit && (
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Topic Type
            </label>
            <div className="grid grid-cols-4 gap-2">
              {(['lesson', 'review', 'quiz', 'assessment'] as const).map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => setTopicType(type)}
                  className={`
                    px-3 py-2 rounded-lg border-2 transition-all text-sm font-medium capitalize
                    ${
                      topicType === type
                        ? 'border-blue-600 bg-blue-100 text-blue-700'
                        : 'border-gray-300 bg-white text-gray-700 hover:border-blue-400 hover:bg-blue-50'
                    }
                  `}
                >
                  {type}
                </button>
              ))}
            </div>
            <p className="mt-2 text-xs text-gray-500">
              Optionally mark this topic as a review, quiz, or assessment
            </p>
          </div>
        )}

        {/* Custom Input Field */}
        {useCustomInput && !isEdit ? (
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Topic Name *
            </label>
            <input
              type="text"
              value={customTopicName}
              onChange={(e) => setCustomTopicName(e.target.value)}
              placeholder="Enter topic name..."
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
            <p className="mt-2 text-xs text-gray-500">
              Enter a custom name for this topic
            </p>
          </div>
        ) : (
          <>
            {/* Letter Grid with Form Selector */}
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 mb-3">
                Select an Arabic Letter *
              </label>

              <ArabicLetterGrid
                value={selectedLetter?.letter || ''}
                onChange={(value) => {
                  const letter = letters.find(l => l.letter === value);
                  if (letter) handleLetterSelect(letter);
                }}
                loading={lettersLoading}
                showFormSelector
                selectedForm={selectedForm}
                onFormChange={setSelectedForm}
              />

              {!selectedLetter && (
                <p className="mt-2 text-xs text-gray-500">
                  Click a letter to create a topic for teaching that letter
                </p>
              )}
            </div>
          </>
        )}

        {/* Form Actions */}
        <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
          <button
            type="button"
            onClick={handleClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={
              (useCustomInput ? !customTopicName.trim() : !selectedLetter) ||
              isCreating ||
              isUpdating
            }
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isCreating || isUpdating
              ? 'Creating...'
              : isEdit
              ? 'Update Topic'
              : 'Create Topic'}
          </button>
        </div>
      </form>
    </Modal>
  );
}
